### ISSUE TITLE
Classes could not be found

### ISSUE THREAD

**Issue by mehdinewdesign** [chiuki/sliding-pane-layout#4]
Hi...
I have this problem in my main Activity , when i use this library it shows this problem:

The following classes could not be found:
- com.sqisland.android.CrossFadeSlidingPaneLayout

Please help me for fixing this error.

Mehdi.newdesign@gmail.com
Thanks...

**Comment by chiuki** [comment]
This is not a library. To use the code, you need to copy and paste the relevant classes into your own project.
